import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-950 text-white`}
      >
        <header className="sticky top-0 z-50 border-b border-zinc-800 bg-zinc-900/90 backdrop-blur">
          <div className="mx-auto flex w-full max-w-6xl flex-col gap-3 px-4 py-3 sm:h-16 sm:flex-row sm:items-center sm:justify-between">
            <Link href="/" className="text-xl font-semibold tracking-tight">
              PanelPlay
            </Link>
            <nav className="flex flex-wrap items-center gap-3 text-sm font-medium text-zinc-300 sm:justify-end">
              <Link className="hover:text-white transition" href="/">
                Home
              </Link>
              <Link className="hover:text-white transition" href="/explore">
                Explore
              </Link>
              <Link className="hover:text-white transition" href="/dashboard">
                Dashboard
              </Link>
              <Link className="hover:text-white transition" href="/create-comic">
                Create Comic
              </Link>
              <Link
                className="hover:text-white transition"
                href="/ai/story-helper"
              >
                AI Story Helper
              </Link>
            </nav>
          </div>
        </header>
        <main className="min-h-screen bg-zinc-950">{children}</main>
      </body>
    </html>
  );
}
